### ISSUE TITLE
Wrong fraction for HUF

### ISSUE THREAD

**Issue by RandolfTjandra** [Rhymond/go-money#114]
https://github.com/Rhymond/go-money/blob/aa7f5f87cfb0203f494896b9216baef4d8133552/currency.go#L112

https://en.wikipedia.org/wiki/Hungarian_forint

Should be 2

**Comment by Rhymond** [comment]
fixed in https://github.com/Rhymond/go-money/commit/59433553bdc4c27fac21acdba27257d489930a4d
