### ISSUE TITLE
Question about the rounding for NewFromFloat

### ISSUE THREAD

**Issue by TimothyIp** [Rhymond/go-money#118]
Love the new addition of `NewFromFloat`. Just wanted to get a clearer understanding of always rounding trailing decimals down when given.

```Go
 cents := money.NewFromFloat(99.999999, money.USD)
 //->  cents: 9999
```

Just want to know the why between getting 9999 vs 10000?

Thanks!

**Comment by Rhymond** [comment]
Hi @TimothyIp 
To be honest there was not much of a discussion about this new feature. The current formula:
```
int64(99.9999 * 10^(fraction))
```
The rounding is done by casting float to integer and this is how it works in Go. 
Maybe @npinochet can give you a bit more details

**Comment by npinochet** [comment]
> The rounding is done by casting float to integer and this is how it works in Go.

That's correct, I made the function thinking more about simplicity rather than usability.
Maybe we can have the discussion here, I think rounding is aceptable in this case, the formula can be adjusted for it:
```
factor = 10^fraction
int64((99.9999 + 0.5 / factor) * factor)
```

**Comment by TimothyIp** [comment]
Just want to give thanks to the both of you for taking the time out of your day for answering this question of mine.

I can see the winner being simplicity here. I just went down a rabbit hole of all the different ways you can round cents (round down, round up, banker's rounding, ...etc). 

I could see it just being as simple as having the consumer provide the float into `NewFromFloat` already rounded to their specific use case. (Which will solve my use case)

As for changing the internals of the function, that part i'm unsure of. I'm with keeping the behaviour in line with Go, since this rounding topic can get quite opinionated. 

An additional function could be added that would do the explicity rounding for the float, something like `NewFromFloatRounded`.

**Comment by TimothyIp** [comment]
Hopefully, this convo will help for posterity if someone needs specific rounding for a use-case and how they can achieve this with `NewFromFloat`.  Going to close this. Thanks!
