### ISSUE TITLE
There is no ZWL currency 

### ISSUE THREAD

**Issue by dkasenka** [Rhymond/go-money#131]
Hi guys

I've found out that the library doesn't include [ZWL](https://en.wikipedia.org/wiki/Zimbabwean_dollar_(2019%E2%80%93present)).
https://github.com/Rhymond/go-money/blob/master/currency.go#L48

ZWL must replace ZWD according to ISO_4217: https://en.wikipedia.org/wiki/ISO_4217

Please fix it.

**Comment by Rhymond** [comment]
Hi

Thanks, you can create PR and include missing currency. Please create a new record in the list to keep backwards compatibility, I think for now we should keep both currencies.

**Comment by dkasenka** [comment]
Also ZWD code [must be 716](https://en.wikipedia.org/wiki/ISO_4217#Historical_codes) instead of 932
