### ISSUE TITLE
How can I multiply a float number?

### ISSUE THREAD

**Issue by LintaoAmons** [Rhymond/go-money#134]
I'm basically want to convert money from one currency to another, here's my idea.

But multiply does not support float type

So what's the best way to achieve this?

```go
func Test_MoneyMultiply(t *testing.T) {
	sgdMoney := money.NewFromFloat(100.23, "SGD")
        exchangeRate := 5 // TODO: What about the current exchangeRate is 5.3? How can I achieve this?
	tmp := sgdMoney.Absolute().Multiply(int64(exchangeRate))
	convertedCnyMoney := money.New(tmp.Amount(), "CNY")

	fmt.Println(sgdMoney.Display())
	fmt.Println(convertedCnyMoney.Display())
}
```

**Comment by Rhymond** [comment]
We have not yet used conversion in our projects, but I believe it would make an excellent addition as a new feature. Here's an example implementation:

```
// Convert creates and returns a new instance of Money with the converted amount
// multiplied by a given rate. The final currency amount is rounded.
func (m *Money) Convert(code string, rate float64) *Money {}

// Example of usage:
sgd := money.NewFromFloat(100.23, "SGD")
cny := sgd.Convert("CNY", 5.3)

fmt.Println(sgd.Display()) // 100.23
fmt.Println(cny.Display()) // 531.22

```

Do you @LintaoAmons think this implementation would cover your use case? Would you be willing to implement it?

**Comment by LintaoAmons** [comment]
I saw their is no dependency in this project, but my noob mvp version depends on the `shopspring/decimal` module.

My noob mvp version here...

```
package moneyutil

import (
	money "github.com/Rhymond/go-money"
	"github.com/shopspring/decimal"
)

// SGDtoCNY converts SGD to CNY based on the given exchange rate
func SGDtoCNY(sgdMoney *money.Money, exchangeRate float64) *money.Money {
	sgdAmount := decimal.NewFromInt(sgdMoney.Amount()).Div(decimal.NewFromInt(100))
	cnyAmount := sgdAmount.Mul(decimal.NewFromFloat(exchangeRate)).Round(2)
	cnyMoney := money.New(int64(cnyAmount.Mul(decimal.NewFromInt(100)).IntPart()), "CNY")
	return cnyMoney
}
```

**Comment by cameronelliott** [comment]
This is such a cool idea, I was looking for this feature.

I really wonder about the issues introduced by using floating point numbers for the ratio of exchange though.

As you know, floating point numbers are generally discouraged from being using for monetary amounts,
and I think by extension for the ratio of exchange.

Maybe the use of Bigints, or maybe taking two int64's as a ratio would be a solution?
(two int64s wouldn't mean a new dependency. Which is a bonus)

References:
https://dzone.com/articles/never-use-float-and-double-for-monetary-calculatio
https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by LintaoAmons** [comment]
> https://github.com/LintaoAmons/go-money

@cameronelliott Here's my fork, it depends on [shopspring/decimal](https://github.com/Rhymond/go-money/issues/github.com/shopspring/decimal).

https://github.com/LintaoAmons/go-money/blob/a21b7c2bdfad5678304a88dc189e7b8e1a45c0a5/money.go#L24

I replace the core type from `int64` to `shopspring/decimal` to allow more type of calculations.

But this change is only to cater my own requirements, you can take a look if you want.
