### ISSUE TITLE
Fractional accuracy for small units. (tenths of a cent for USD)

### ISSUE THREAD

**Issue by systemmonkey42** [Rhymond/go-money#148]
Hi, 

I'm dealing with credit card transactions where the fees/charges are calculated up to 5 decimal places.

Using 'go-money' the fees are rounded to whole cents and all the totals are immediately wrong.

I would need to record fractional cents in a database, and allow calculcations with higher precision.  Rounding is only
acceptable for display, not storage.

Is there a flags or something I can tweak to allow for higher resolution calculations?

Thanks

**Comment by Rhymond** [comment]
Hey @systemmonkey42,

In your case I would create new currency using 

```
// AddCurrency lets you insert or update currency in currencies list.
func AddCurrency(code, Grapheme, Template, Decimal, Thousand string, Fraction int) *Currency {
	c := Currency{
		Code:     code,
		Grapheme: Grapheme,
		Template: Template,
		Decimal:  Decimal,
		Thousand: Thousand,
		Fraction: Fraction,
	}
	currencies.Add(&c)
	return &c
}
```

where you can set your preffered fraction (in your case 5).
