### ISSUE TITLE
Global calculator variable will cause races

### ISSUE THREAD

**Issue by tylerb** [Rhymond/go-money#16]
Right now there is a `calculator` variable that is global and created anew every time a money instance is created.

This is an issue and will cause races. Multiple money objects being created and used on multiple goroutines will cause indeterminate results due to the races.

The `calculator` instance should be inside the `money` instance, and be created in the `money` constructor.

**Comment by tylerb** [comment]
I can submit a PR for this once #15 is merged.

**Comment by Rhymond** [comment]
@tylerb merged and new release (v0.3.0) was created
