### ISSUE TITLE
Use of int causes overflows and arch-specific variability

### ISSUE THREAD

**Issue by bbrks** [Rhymond/go-money#3]
Using the architecture-independent `int` type will cause 32-bit binaries to overflow if more than `21,474,836.47` is used in a base-100 currency, introducing architecture-dependent behaviour differences which may not be caught.

This can be resolved by switching amounts to use the `int64` data type. This will still work on 32-bit architectures, at the slight expense of performance, and allow base-100 currency values up to an amount of `92,233,720,368,547,758.07` ... More than likely enough for most consumers of this package :)

**Comment by Rhymond** [comment]
Hi @bbrks, Thanks for suggestion.
Where is plans for [Big](https://golang.org/pkg/math/big/) signed int implementation in order to sum larger values. 
What you think about it? Does it much slower than int64?

**Comment by tylerb** [comment]
From what I've read, Big is pretty slow compared to int64. I think the range provided by int64 would be just fine for the foreseeable future. If someone comes along needing Big support, it could be addressed at that time.

**Comment by bbrks** [comment]
Whilst pre-1.0 (and no API-stability guarantee), a quick fix would be to switch to int64... but keep in mind that any type changes in future will cause a breaking change of the API.

I have not used the Big package personally, so cannot vouch for it's appropriateness or performance.

**Comment by tylerb** [comment]
Another option would be an interface type defined by this package that exposes methods for retrieving the internal value as various types. Right now it seems we only have a `Display` method, which isn't super useful.

`type Amount interface` which defines methods for all the appropriate integer types would be excellent. It could be extended to include a Big type, later, if necessary. This would allow the internals to change without breaking existing implementations.

**Comment by Rhymond** [comment]
Thank you @bbrks int64 was implemented on v0.3.0 release:
https://github.com/Rhymond/go-money/pull/15
