### ISSUE TITLE
Add currency of Myanmar (MMK)

### ISSUE THREAD

**Issue by namco1992** [Rhymond/go-money#33]
Hi Rhymond,
thank you for creating this amazing tool!
I noticed that there is no support for the currency of Myanmar, may I create a PR and add it? thanks!

**Comment by Rhymond** [comment]
Hi @namco1992,

Thank you! Yes sure you can, I would really appreciate it.

**Comment by namco1992** [comment]
Hi, @Rhymond ,
thanks for the reply, I will work on it and create a PR later.
