### ISSUE TITLE
SQL Compatibility (GORM and other)

### ISSUE THREAD

**Issue by Toasterson** [Rhymond/go-money#37]
Hello

I am a happy user of go-money and use it in a private webapp with database.

I had to make some adaptations to make go-money usefull most notably I had to add sql compatibility. As I did not want to make changes to go-money at that time I just wrapped go-money into another struct and copy data into and out of the go money struct on read/write to the database. Needless to say I am not a fan of that solution but it worked for my needs.

Now that I have some time on my hands, I would like to implement that Feature into go-money directly so that Life is easier for me.

What I did was implement Scanner and Valuer Interface and save the Data as  semicolon delimited string in the Database. That was enough to save amount and currency information for later Object reconstruction during Read.

Would you like to keep that implementation or do you have another idea in what format to save the Data to database?

I could also make Inherited types so that the Main type does not force a certain usage over another.

what are your thoughts on this?

**Comment by Rhymond** [comment]
Hi,

To create a Money object you need two parameters. Amount and Currency.
It really depends what datastore (database solution) you're using.
If you're using relational database, my suggestion would be to have two columns. Integer column for Amount and String or Enum (if you want to be fancy) for Currency.

You can get `Currency` by calling:
```
currency := money.Currency()
```

And `Amount`:
```
amount := money.Amount()
```

Just save those and you're good to go.

**Comment by Rhymond** [comment]
this issue has been closed because it has been inactive
