### ISSUE TITLE
Does not have i18n for formatting ?

### ISSUE THREAD

**Issue by gedw99** [Rhymond/go-money#39]
Am building a templating system and need to handle currency properly.
Does this library have functionality for this ?
E.g in Sweden and Germany money is displayed differently 

If you know of I lib I can combine and PR if you want too

**Comment by Rhymond** [comment]
Hi @gedw99, 

Could you give me an example?
At the moment you can create new currency using `money.AddCurrency()` 
(https://github.com/Rhymond/go-money/blob/master/currency.go#L152)

You can create new currency for each language (or languages which requires different display.

**Comment by gedw99** [comment]
hey @Rhymond  
then it might work from what your said.
I need to to take unit of money and display it correctly according to the users locale.

Can you point me to the relevant code as i cant find it.

**Comment by Rhymond** [comment]
Have you tried?
https://github.com/Rhymond/go-money/blob/master/currency.go#L152
This function?
