### ISSUE TITLE
Non-idiomatic error handling / log.Fatal

### ISSUE THREAD

**Issue by bbrks** [Rhymond/go-money#4]
Packages should return errors so that the consumer of the package can choose what happens.

Packages should not log things, and they should not exit the application via `log.Fatal`

Panics in packages are somewhat acceptable if some startup dependency is incorrect and the package cannot work without it.

Fixing this will require a change in the API, and thus should require a version increment.

**Comment by Rhymond** [comment]
Hi @bbrks, log.Fatals was removed and new version published:
https://github.com/Rhymond/go-money/tree/v0.1.0
