### ISSUE TITLE
Tag latests release

### ISSUE THREAD

**Issue by jhuliano** [Rhymond/go-money#40]
Hello,
is there any plan to make a new release/tag following the semantic versioning?
Seems like the latest release was [v0.3.6](https://github.com/Rhymond/go-money/tree/v0.3.6) on Oct 31, 2017.
I'm specifically interested on the PR https://github.com/Rhymond/go-money/pull/36 that adds CHF currency, merged to master on Jul 25, 2018.

**Comment by Rhymond** [comment]
Hi,
New version is created (v0.3.7) with latest changes.
Thanks for pointing this out
