### ISSUE TITLE
Add go.mod

### ISSUE THREAD

**Issue by HT808s** [Rhymond/go-money#41]
Creation of a go.mod file in compliance with go new way of handling dependencies.

@Rhymond what do you think of it ?

**Comment by Rhymond** [comment]
@HT808s great idea! Do you want to create PR for this?

**Comment by HT808s** [comment]
Sure, I'll be glad to do it !

**Comment by Rhymond** [comment]
@HT808s Thank you again! It's now in v0.3.8 release
