### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by logitick** [Rhymond/go-money#43]
Running `go get github.com/rhymond/go-money` fails and spits out the message:
```
go: github.com/rhymond/go-money@v0.3.8: parsing go.mod: unexpected module path "github.com/Rhymond/go-money"
go: error loading module requirements
```

seems to be related to https://github.com/golang/go/issues/27154

**Comment by Rhymond** [comment]
hi @logitick,

Strange I can't replicate this. What Go version you're using?

**Comment by HT808s** [comment]
Hi there,
The module path is case-sensitive and must match the path requested of `go get`.
Found  here golang/go#27154,

So in this case you need to do `go get github.com/Rhymond/go-money@v0.3.8`

**Comment by HT808s** [comment]
Maybe we can manually update the `go.mod` to lowercase the path.
But I don't know if then `go get` will be able to find the dependency from github since the URL (https://github.com/Rhymond/go-money) is not lowercase.

**Comment by logitick** [comment]
doh! `go get github.com/Rhymond/go-money` worked. Thanks!
