### ISSUE TITLE
Add possibility for custom formatter

### ISSUE THREAD

**Issue by th3noname** [Rhymond/go-money#5]
When calling the Display() method for a given object i get the following output:
`€1,000.00`
But the correct german format is `1.000,00 €` (in most cases; sometimes it would be `€ 1.000,-`). This format varies even between different EURO countries. And then there is the problem with dot and comma as decimal marks.

That's why it would be nice to define a custom formatter before calling Display().

**Comment by Rhymond** [comment]
Hi @th3noname, 
Thanks for your suggestion, 
We plan to implement this feature in v0.3.0 version

**Comment by Rhymond** [comment]
I implemented this feature, now you can add currencies by `money.AddCurrency()` function
