### ISSUE TITLE
JSON Marshal & Unmarshal

### ISSUE THREAD

**Issue by maeglindeveloper** [Rhymond/go-money#52]
Hi everyone, 

I'm actually trying to marshal / unmarshal the **Money** structure but, obviously because of the current implementation, it is not possible yet.

I saw that someone has already required a PR regarding that topic :

https://github.com/Rhymond/go-money/pull/38

Will it be validated ? I think it is a really important feature 👍 
Thanks by advance ! 

@Rhymond

**Comment by maeglindeveloper** [comment]
Any update on this one guys ? :( 
@Rhymond

**Comment by Rhymond** [comment]
Hi @maeglindeveloper, sorry for a late response. I'm going to take a look today. I'm a bit worried that it is not backwards-compatible change and people who JSON marshal money now, going to have different JSON structure. /cc @eddieowens Do you think we can avoid this?

**Comment by Rhymond** [comment]
Released with v1
