### ISSUE TITLE
Retrieve currency and amount

### ISSUE THREAD

**Issue by th3noname** [Rhymond/go-money#6]
It would be helpful to retrieve the `currency `and `amount `information from a `money` object.

**Comment by tylerb** [comment]
I'll submit a PR to make `amount` accessible once #17 is merged.

@Rhymond I'm thinking we just have an `Amount() uint64` method on `Money`. Thoughts?

**Comment by mrd0ll4r** [comment]
I'd also be interested in the `currency` to check whether it is one specific currency. I don't want to allocate a dummy `Money` struct just to call `SameCurrency` with it, that just doesn't feel right.

**Comment by Rhymond** [comment]
@mrd0ll4r now you can reach Currency object by `Money.Currency()`
Big thanks for @jeffandersen
