### ISSUE TITLE
HUF and TWD should have Fraction: 2

### ISSUE THREAD

**Issue by patanachai** [Rhymond/go-money#61]
This is from https://en.wikipedia.org/wiki/ISO_4217
Also, all payment providers, I deal with they use fraction of 2 instead of 0

**Comment by Rhymond** [comment]
hello @patanachai,

Could you create PR for this? It would be really helpful.

**Comment by epishovska** [comment]
TZS should has fraction 2 instead of 0 (https://en.wikipedia.org/wiki/ISO_4217)

**Comment by epishovska** [comment]
There are lot of currencies that stripe use and they are not included here. It would be nice if we include them here. (https://stripe.com/docs/currencies)
Also the following currencies should have the following fractions instead of 0:
COP -> fraction 2
HUF -> fraction 2
UYU -> fraction 2

**Comment by karel-3d** [comment]
Why have all this custom-baked, when there is `golang.org/x/text/currency` which has all this info, and has it correctly.

**Comment by salanfe** [comment]
@karelbilek the list is far from being complete in `golang.org/x/text/currency` ([link](https://github.com/golang/text/blob/master/currency/currency.go#L146)) isn't it ?

**Comment by Rhymond** [comment]
fixed https://github.com/Rhymond/go-money/commit/59433553bdc4c27fac21acdba27257d489930a4d
