### ISSUE TITLE
Suggestion: Provide constant values for currency codes

### ISSUE THREAD

**Issue by jamesallured** [Rhymond/go-money#72]
Like the [net/http package status codes](https://golang.org/pkg/net/http/#pkg-constants) and [the use of `time.Second` etc. in the time package](https://golang.org/pkg/time/#pkg-constants), I suggest providing currency codes as public constants.

I understand that they would represent a string of the same name but would make it easier to ensure that the currency code you're using is correct through autocompletion in editors.

I wanted to gather some feedback on this before having a go at implementing it. It shouldn't change the API as the constants will just act as helpers that can be used instead of passing a string literal as an argument, for example:

```go
pound := money.New(100, money.GBP)
```

**Comment by lombartec** [comment]
+1 from me, i was looking for those constants the first couple of times using this package

**Comment by hebime** [comment]
This would be a nice addition IMO. +1

**Comment by sheghun** [comment]
Since this issue has been fixed can we close this now @jamesallured
