### ISSUE TITLE
Issues with first example in Readme.md

### ISSUE THREAD

**Issue by peteArnt** [Rhymond/go-money#76]
I tried to run the first example in the Readme.md text.
Two issues immediately show up:
1. The Example does not import "log" (I had to add  the import).
2. When I compiled and ran the example, absolutely nothing printed on the console.
Am I missing something?
Regards,
-P.

**Comment by Rhymond** [comment]
Sorry for the late response. 
First, I will probably change `log.Fatal` to `panic` to ensure there is no confusion.
Secondly, `Display()` function doesn't print anything and just returns the `money` in representable format. You can print it by wrapping it with `fmt.Print()`
