### ISSUE TITLE
wrong fraction length

### ISSUE THREAD

**Issue by leminhson2398** [Rhymond/go-money#86]
@Rhymond friend
please take a look at: https://github.com/Rhymond/go-money/blob/7ee9cdfb3d7c940ede96154959b8376d5647948a/currency.go#L176
i think the Fraction field is wrong.
It should be 2 instead of 0

E.g: If i check it in python:
```python
from babel.numbers import get_currency_precision

CODE = "VND"

print(get_currency_precision(CODE))

#result 
>>> 2
```

**Comment by leminhson2398** [comment]
@Rhymond friend!
There is another library named go-accounting. I think their implementation is different from yours.
Take a look at: https://github.com/leekchan/accounting/blob/17a4ce5f94d4d6b8115c2c6f39f7f2e8cb8f27f0/locale.go#L189

If i am wrong. Please let me know why and i appreciate it.

**Comment by Rhymond** [comment]
@leminhson2398 it looks like the correct fraction by the ISO standards is `0` for VND currency

**Comment by leminhson2398** [comment]
@Rhymond Initially I thought you were wrong, but VND is low rate currency, if it has fraction part, we do not have small enough units to pay (the smallest is hundred unit). So I think the go accounting library has a mistake, not yours.

Thank you
